<a href="https://colab.research.google.com/github/zh-yng/Pytorch-Tutorial-Youtube/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATIONS**
- Add, Subtract, Multiply, Divide, Remainders, Exponents
- Shorthand and Longhand
- Reassignment

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
# addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
# addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
# subtraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [6]:
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [ ]:
# multiplication
tensor_a * tensor_b

In [ ]:
torch.mul(tensor_a, tensor_b)

In [ ]:
# division (auto-converts answer components to float)
tensor_b / tensor_a

In [ ]:
torch.div(tensor_b, tensor_a)

In [ ]:
# remainder
tensor_b % tensor_a

In [ ]:
torch.remainder(tensor_b, tensor_a)

In [ ]:
# exponents / power
tensor_a ** tensor_b

In [ ]:
torch.pow(tensor_a, tensor_b)

In [8]:
# reassignment
# YOU CAN DO tensor_a = tensor_a + tensor_b
# OR you can use operation as an instance method
# putting an UNDERSCORE after the identifier to assign
tensor_a.add_(tensor_b)
tensor_a

tensor([11, 14, 17, 20])